// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdtptveoanfucckpkmvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkdHB0dmVvYW5mdWNja3BrbXZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMjU2ODQsImV4cCI6MjA2MjgwMTY4NH0.Ny6hikgPnnEBjLaC5NXYWpYOuWtqfIIbRPOHhXHeaJo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);